### ISSUE TITLE
Adding unread tag to message does not change message on server to unread

### ISSUE THREAD

**Issue by nickwynja** [elizagamedev/mujmap#24]
The changes to sync unread states in neomutt is working nicely! There's one issue I've found: If I mark a message as unread locally, either through neomutt's `<toggle-new>` or update the notmuch tag to `unread`, then sync, the change isn't reflected on the server.

`notmuch search tag:unread` properly shows the message, so it's not a neomutt to notmuch issue.

This is the the trace log for `Email/changes`. Does this mean mujmap is not attempting to push any changes to the server?

```
[2022-05-30T17:19:23Z TRACE mujmap::remote] Post response: {"sessionState":"cyrus-581349;p-72a2823c15","methodResponses":[["Email/changes",{"destroyed":[],"updated":[],"newState":"612383","hasMoreChanges":false,"oldState":"612383","created":[],"accountId":"u41f441db"},"0"]]}
```

**Comment by elizagamedev** [comment]
Hmm, it's hard to say what might be happening, but I wouldn't count out maildir flag/neomutt weirdness quite yet. Did you do a full refresh before or after updating to the maildir flags build? I might try to reproduce but I've never used mutt before.

The `Email/changes` method is actually used to retrieve changes made on the server, not from notmuch. The relevant logs for setting email properties (`Email/set`) are closer to the end of program execution.

**Comment by elizagamedev** [comment]
Unfortunately I've given up on trying to repro in mutt for the time being because trying to set up and learn mutt has become a project in its own 😅

I haven't been able to reproduce by flagging emails as read/unread manually with the latest revision of notmuch, either. Some thoughts:

1.  Perhaps it's due to neomutt/maildir flag weirdness as I mentioned earlier.

    I wonder if maybe neomutt is renaming the files on the disk, but not applying the notmuch tags, but notmuch itself sees the new filenames and implicitly adds an unread tag, or something weird like that? Perhaps try something like (if you haven't already):

    ```shell
    notmuch tag +unread -- tag:inbox
    ```

    to flag every email in your inbox as unread, then synchronize and see if Fastmail looks correct.
2.  Perhaps it's another slight difference in the way our accounts are set up on Fastmail's servers triggering a bug.
3.  Perhaps it's due to a duplicate message causing weird undefined behavior.  There were some fixes pushed for that a while back, but it's possible this is still happening in some edge cases. I did encounter some unread strangeness due to this issue at the time, though.
4.  Perhaps it's due to a difference in the way neomutt and Fastmail handle the unread state of threaded messages.

**Comment by nickwynja** [comment]
Well, shoot. I'm sorry to have wasted your time chasing this without better repro steps. `notmuch tag +unread -- tag:inbox` then a `mujmap sync` (built from the most recent commits) does in fact update the server. I had assumed that seeing the `unread` tag in notmuch meant that things would act the way that `notmuch tag +unread` would behave, but silly me.

Must be something strange about how neomutt sets the unread flag with notmuch then. I'll look through the neomutt issues to see if there's anything relevant since I'm seeing inconsistent and inexplicable behavior that I've never noticed with lieer as well.
