### ISSUE TITLE
Maildir flags are not set

### ISSUE THREAD

**Issue by robn** [elizagamedev/mujmap#8]
I've been trying to use mujmap with neomutt today, which has some support for notmuch but its not entirely there.

It treats the maildir flags as the source of truth, and so when reading a mujmap-generated maildir thinks that all messages are unread and not flagged.

When a message is changed (eg user reads one) it triggers a flag update in notmuch. Because it didn't know the original flags, it sends the wrong set out to notmuch, and from there to the JMAP server.

(and because I accidentally touched the whole inbox in neomutt, all my inbox is unread. Fortunately I'm used to my email being chaos, hah).

(arguably neomutt is doing the wrong thing by using the maildir flags, and I might yet go back to it but I've been inside it before and its .. not pretty).

So! I thought to make mujmap set the file flags right. My first dumb attempt was to just plug in notmuch's own support for this:

```diff
diff --git a/src/local.rs b/src/local.rs
index a664a32..80288ba 100644
--- a/src/local.rs
+++ b/src/local.rs
@@ -308,6 +308,7 @@ impl Email {
         for tag in tags {
             self.message.add_tag(tag)?;
         }
+        self.message.tags_to_maildir_flags()?;
         self.message.thaw()?;
         Ok(())
     }
```

Alas, that really seems to assume that we're letting notmuch manage the maildir, but since mujmap is it just results in this madness:

```
$ ls -l Mf5091b2cd9e2f9c3fe4f4166.Gf5091b2cd9e2f9c3fe4f4166b1e7877cbfad1b5e*
-rw-r--r-- 1 robn robn 54315 May 15 12:52 Mf5091b2cd9e2f9c3fe4f4166.Gf5091b2cd9e2f9c3fe4f4166b1e7877cbfad1b5e
lrwxrwxrwx 1 robn robn   117 May 15 17:16 Mf5091b2cd9e2f9c3fe4f4166.Gf5091b2cd9e2f9c3fe4f4166b1e7877cbfad1b5e:2,F -> '/home/robn/.cache/mujmap/!home!robn!mail!grue!cur!Mf5091b2cd9e2f9c3fe4f4166.Gf5091b2cd9e2f9c3fe4f4166b1e7877cbfad1b5e'
```

That is, a dangling link to the message file in the cache, since moved into the maildir.

So maybe notmuch's own support for this can be made to work but I think it would require changes to how mujmap puts together its storage, which is rather beyond my knowledge (I actually had never used notmuch before today).

So thing mujmap would have to do is add flags when making the filename, but it would also need to grow support for renaming files when the flags change. I don't think that's too hard to do, but I definitely have no idea whether this is something mujmap should be doing. That's likely your call.

I will play around with this and with neomutt a bit more over the next week as time permits to try and figure out what the best solution is. Your thoughts welcome!

**Comment by elizagamedev** [comment]
Thanks for finding this, I haven't used neomutt so I probably wouldn't have discovered this issue myself. It's definitely a bug that mujmap doesn't properly respect notmuch's maildir flags. I think the approach to fix this I like best is:

- Check the notmuch config with `Database::config_list()` for `maildir.synchronize_flags`, and enable flag synchronization in mujmap if so.
- After the call to `thaw()` (at least, I think it should be after `thaw()` but the docs are kind of ambiguous), call `tags_to_maildir_flags()` in case `synchronize_flags` is enabled.
- Instead of re-using the same maildir path in the `MailFile` object when replacing the symlink, re-read the maildir path from the `Message`.

**Comment by robn** [comment]
That last point seems key. I will take a swing at it tonight. Thanks!

**Comment by elizagamedev** [comment]
I actually have some bad news--I was investigating, and it seems like `Database::config_list()` only reads flags set for the database itself, *not* the config file. There are a whole other set of config functions not implemented in `notmuch-rs` which *actually* return all of the config. In order to properly fix this bug, an upstream PR to add those missing APIs is a prerequisite. I can work on upstreaming those APIs if you'd like to focus on fixing the behavior of mujmap itself.

**Comment by robn** [comment]
Ok, I will try!

**Comment by elizagamedev** [comment]
I submitted a PR at vhdirk/notmuch-rs#44 which adds the necessary API:

``` rust
// `Ok(true)` if sync is enabled.
db.config_bool(ConfigKey::MaildirFlags)
```

**Comment by robn** [comment]
Nice one! Currently down a deep rabbithole understanding what you've built here, hopefully something to show in an hour or two. Thanks for the opportunity and guidance :bow:
